### ISSUE TITLE
PxArticulationJointReducedCoordinate - Set Drive Target & Velocity

### ISSUE THREAD

**Issue by Tadinu** [NVIDIAGameWorks/PhysX#139]
https://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/Articulations.html#joint-positions-and-velocities

Can you give a practical example of how to use `PxArticulationJointReducedCoordinate`'s `setDriveTarget` & `setDriveVelocity` either independently or together?

How do I order a joint to reach a position with some specific velocity?
By using `setDriveTarget`, the joint would be already actuated and given some acceleration, which is generated by some force/torque (as my guess due to its child link's stiffness and damping) from an underlying built-in PD Controller. So what would happen if I incorporate the use of `setDriveVelocity` in this case and how to do that properly?

Thanks,

Tad.

**Comment by kstorey-nvidia** [comment]
The stiffness term in the drive drives towards the drive target (position/angle). It introduces forces that are proportional to the joint angle error (drive target - joint position) to drive the joint towards zero error (joint angle == drive target).

The damping term drives the joint towards a target velocity. It applies forces proportional to the velocity error (drive velocity - joint velocity) to drive the joint towards zero joint velocity error (joint velocity == drive velocity).

Generally, if you are using a positional drive target, you need to have some stiffness term that is strong-enough to move the system to the target angle. If the drive is very stiff, there is a chance of overshooting and then oscillating around the target angle like a spring. The PD controller actually uses a spring formula that is implicitly damping, so it generally works well. However, you can optionally add some damping to reduce overshoot/oscillation. In this scenario, I would expect that the drive velocity would be zero.

If you are driving towards a target velocity, you will usually have only a damping term and no stiffness term, because in this case the drive velocity and drive target would very likely fight against each other in an undesirable way.

It may be that you can make these 2 terms play nicely together if you are setting a non-zero target velocity and target position that both lead to the same target angle (for example) but, in that case, there doesn't seem to be much point in setting the target velocity IMO because you should get the same results using a target pose and using either no damping, or a small amount of damping with zero target velocity.

**Comment by Tadinu** [comment]
Thanks a lot for your clarification, @kstorey-nvidia! I also observed that with my stiffness and a bit damping setting, the joint could reach its target position quite well using just `setDriveTarget` only.
So I should stick with it then.

**Comment by Tadinu** [comment]
@kstorey-nvidia, just an extra question, so it seems if I don't use `setDriveVelocity` at all, if I would speed up or slow down the joint in a  trajectory, the only way is to adjust `stiffness` and `damping` on the way?

**Comment by kstorey-nvidia** [comment]
Right. If you want to speed up how responsive your drive is, you have to adjust the stiffness and make it stiffer. The force applied is proportional to error  error*stiffness - velocity * damping.

SetDriveVelocity is more for the case where you want to set a constant drive velocity and have the drive translate/spin for an amount of time. You could get the same effect using drive targets but that means that the application has to work out a target pose each frame.

**Comment by Tadinu** [comment]
I'm clear now. Thank you!
