### ISSUE TITLE
It is possible to use an amd graphics card as a primary and a second  PhysX card ?

### ISSUE THREAD

**Issue by manotroll** [NVIDIAGameWorks/PhysX#310]
in the past with pci-e boards, it was possible, but as they are not manufactured, I wonder if I can do that today
in case use for example a rx 590 for graphics and a 1030 for physics

**Comment by amoravanszky** [comment]
This is a good question.  I don't know, its neither a feature we explicitly support, nor one we explicitly disallow, so if it works it will be by accident rather than design.  The PhysX dev team doesn't have any AMD GPUs so we cannot even easily test it.  If it doesn't work the problem could be anywhere from our host side code to any of the drivers involved...quite a can of worms.
