### ISSUE TITLE
Vehicle example in real time

### ISSUE THREAD

**Issue by yumianhuli2** [NVIDIAGameWorks/PhysX#353]
Hello PhysX Team！

I saw in function void stepPhysics() const PxF32 timestep = 1.0f/60.0f;
Does this time step mean 1/60 of a second Vehicle calculation in the real-time case? And then depending on the hardware it's going to be faster than 1/60 of a second, so I have to wait until 1/60 of a second and then do the second loop, So this is a soft real-time simulation,is this right?

Thanks！

**Comment by gyeomannvidia** [comment]
The function stepPhysics() is just a wrapper for the PhysX simulation function calls. 

PhysX will advance the simulation forwards in time by the user-specified timestep as fast as it can.   PhysX only considers simulation time and does not track computer clock time. 

If you want a real-time simulation of vehicles then a separate system is required.  This system needs to track the passing of real time and update the physx scene accordingly so that simulation time matches real time.

**Comment by yumianhuli2** [comment]
> The function stepPhysics() is just a wrapper for the PhysX simulation function calls.
> 
> PhysX will advance the simulation forwards in time by the user-specified timestep as fast as it can. PhysX only considers simulation time and does not track computer clock time.
> 
> If you want a real-time simulation of vehicles then a separate system is required. This system needs to track the passing of real time and update the physx scene accordingly so that simulation time matches real time.

OK，It's like updating with render frames！
