### ISSUE TITLE
Persistent contact reports zero linear velocity change

### ISSUE THREAD

**Issue by pkusilence** [NVIDIAGameWorks/PhysX#404]
I am testing Extra Contact Data with PhysX 3.4.2 included in UE4.26.1 by raising flag ePOST_SOLVER_VELOCITY and ePRE_SOLVER_VELOCITY.  

A sphere with restitution = 0 and friction = 0,  is set Vx=200cm/s in the Tick function (which is ticking while PhysX is not simulating) .  Then the sphere collides with a plane. The result is :  when the touch is found at first, the pre Vx=200 cm/s and the post Vx=16cm/s (which seems ok for me);  when the contact keeps ( persistent) , the pre and post velocities remain exact the same. Which maybe means the solver does not change the velocity. However, the Vx is getting close to zero as the simulation step forward.

So I followed how the engine works , finding:  for PersistentContact case,  the contact solver is excute before velocity is written into the stream, so the Pre and Post velocity is the same one after contact solver.

Could any developer explain these phenomena?

**Comment by kstorey-nvidia** [comment]
I will file an internal bug to investigate because this seems like a bug.

One thing to note is that contact reports are reported before the velocity state has been copied to the buffered/external state of the actors, so you can actually get the pre-contact velocity from the respective actors by calling getLinearVelocity()/getAngularVelocity(). The post-contact velocity reported should be correct, so you should be able to work around this to get the expected results.

**Comment by pkusilence** [comment]
Thanks for your reply, it does works, just need to handle vz -= gravity*dt.

**Comment by TwentyPast4** [comment]
I'm also experiencing this problem. Post and Pre seem to  indicate a zero velocity change, while the normal impulse is non-zero
