### ISSUE TITLE
disable/enable self-collision for physx::PxArticulationReducedCoordinate?

### ISSUE THREAD

**Issue by erwincoumans** [NVIDIAGameWorks/PhysX#43]
What is the recommended way to enable/disable self collisions for PxArticulationReducedCoordinate?
A filterShader doesn't seem to help. Do we need to create PxAggregate for the links?

Is there any documentation for the new PxArticulationReducedCoordinate?

I would like to override the 'filterArticulationLinks' method, to avoid all self-collisions for some articulations (not just filter self-collisions between links that are directly parent-child).
~~~~~~~~~~~~~~~~~~
static bool filterArticulationLinks(const ActorSim& rbActor0, const ActorSim& rbActor1)
{
	// If the bodies are articulation links of the same articulation and one link is the parent of the other link, then disable collision
	PxU32 size = rbActor0.getActorInteractionCount();
	Interaction** interactions = rbActor0.getActorInteractions();
	while(size--)
	{
		const Interaction* interaction = *interactions++;
		if(interaction->getType() == InteractionType::eARTICULATION)
		{
			if (rbActor0.getActorCore().getActorFlags() == physx::PxActorFlag::eDISABLE_SELF_COLLISION)
				return true;
			if (rbActor1.getActorCore().getActorFlags() == physx::PxActorFlag::eDISABLE_SELF_COLLISION)
				return true;
			if ((&interaction->getActorSim0() == &rbActor1) || (&interaction->getActorSim1() == &rbActor1))
				return true;
		}
	}
	return false;
}
~~~~~~~~~~~~~~~~~~

Posted the question here, since Adam asked for it here, instead of forum (still, I think forum has some value too): https://devtalk.nvidia.com/default/topic/1046135/physx-and-physics-modeling/please-consider-posting-questions-to-physx-github-issues-directly-/

**Comment by kstorey-nvidia** [comment]
You can implement custom filtering by providing an implementation of PxSimulationFilterShader to PxSceneDesc::filterShader.

By default, you are probably calling PxDefaultSimulationFilterShader. You could probably find a way to use this filter shader to achieve what you would like by working through the code, but the simplest solution might be to implement your own filter shader function and apply your own custom rules to filter shapes.

See here https://docs.nvidia.com/gameworks/content/gameworkslibrary/physx/guide/Manual/RigidBodyCollision.html#collision-filtering for further details.

An alternative is that you could use a broad phase aggregate to filter self-collisions. Filter shaders are a precision tool, while using aggregates to filter self-collisions is more of a blunt instrument. However, they are a simple way to achieve what you asked. You would just need to add the articulation to an aggregate with self-collision disabled.

**Comment by erwincoumans** [comment]
Thanks for the reply Kier!

>> and apply your own custom rules to filter shapes.

How does one detect inside a filterShader that the objects belong to the same articulation?
~~~~~~~~~~~~~~
PxFilterFlags scissorFilter(PxFilterObjectAttributes attributes0, PxFilterData filterData0,
							PxFilterObjectAttributes attributes1, PxFilterData filterData1,
							PxPairFlags& pairFlags, const void* constantBlock, PxU32 constantBlockSize)
~~~~~~~~~~~~~~
>> broad phase aggregate

This works indeed, I had to add the aggregate to the scene, instead of the articulation.

**Comment by kstorey-nvidia** [comment]
Yes, that's right. A set of actors/articulations can be added to an aggregate, which is then added to the scene.

Regarding filtering: the application defines its own filtering rules. PhysX ships with a default filter shader but most game developers find it more convenient to define their own. The default filter shader just gives you some pointers on what you can do (see ExtDefaultSimulationFilterShader.cpp). However, that implementation is maybe a bit more heavyweight than you want.

In your filter shader, you can find out the actor type (rigid body, articulation etc.) using the following method:

PxGetFilterObjectType(attributes).

It will return an enum defining what type of actor it is.

In addition to this, you have PxFilterData for each shape. This is a set of 4 integers, which you can define on each shape by calling PxShape::setSimulationFilterData(...) method. You can use this to store some specific information about the shape (e.g. bit masks for what it should collide with, IDs for the actor/articulation, link index etc.) that you can use to implement your custom filtering rules. PhysX doesn't have fixed-function filtering rules but instead defers it to the application to implement the rules themselves. It's potentially a bit more fiddly to begin with but it eventually results in something that should be more flexible.

For your simple case, you could just look to see if both shapes are an articulation, and embed the articulation ID somewhere in the filter data. If they are both articulations and the articulation ID is the same, kill the pair, otherwise process it. This approach should be flexible-enough to be able to do pair-wise filtering on individual links on an articulation.

**Comment by erwincoumans** [comment]
Great, thanks a lot for your explanation. That'll do ;)
