### ISSUE TITLE
Support for cylinder shapes

### ISSUE THREAD

**Issue by christoph-jaehne** [NVIDIAGameWorks/PhysX#50]
Hello everybody, as a roboticist and being used to the urdf format, I really miss the basic shape of a cylinder. Especially for wheels an approximation with e.g. capsules does not make sense as it overly expands the volume and a mesh seems like overkill for this application.

Any intentions of adding cylinders to the set of supported primitive shapes?

**Comment by kstorey-nvidia** [comment]
You can use a tessellated convex mesh and get very close results to a cylinder. PhysX also supports adding a radius to any arbitrary shape (called "rest offset"), which allows you to introduce rounded edges to any convex shape, e.g. you can use this to make a lozenge-like shape from a box. Basically, you only need to use a capsule if you don't care about the accuracy of collisions at the ends.

If you want to make a cylinder shape, you should just need to sample the circles at the top/bottom of the sphere (e.g. 16 or 32 verts per-face) and pass those vertices to our convex cooking algorithm and the result should be a decent approximation to a cylinder. If you are unhappy with the rolling behaviour, you can improve that by shrinking your cylinder by some small amount and adding that value to the contact and rest offsets. This will result in slightly corners on the cylinder, but improved rolling behaviour.

**Comment by christoph-jaehne** [comment]
Thanks for the hints. I assume that using a mesh here instead of a geometric primitive would be computationally less efficient and also less accurate for rolling contacts as you already mentioned.

So there is no intention to add that feature in the future?

**Comment by kstorey-nvidia** [comment]
There is certainly a potential argument for computational efficiency. In theory, a primitive cylinder collision function could be faster than a convex mesh. However, our convex mesh collision code is pretty quick. We can process 10s of 1000s of convex collision pairs on CPU in approximately 1ms and millions of pairs on the GPU in a similar time slice.

There is currently no intention to add cylinder support. If it turns out that it is absolutely necessary to achieve a certain performance target, or it the behaviour of a convex approximation is unacceptable and can't be resolved by increased tessellation or rest offset inflation, then we may revisit this position.

Here' a video that one of our engineers produced as a response to a similar discussion. As you can see, the behaviour is pretty accurate:

https://www.youtube.com/watch?v=20FrjG1VWpA&t=5s

The same engineer produced the following showreel:

https://www.youtube.com/watch?v=6dATi4-wb3o

He is using 100% CPU PhysX in this showreel. The performance if he was using GPU PhysX would be even larger; he just didn't because none of these scenes ran at below real-time with the CPU implementation.

**Comment by christoph-jaehne** [comment]
The videos really look promising. Meshes it is then ;) Thanks for the infos.

**Comment by Chico63** [comment]
Hi,

I'm in charge of the development of a robotic simulator since 2010 that need to be accurate in order to be useful.
Integration of cylinder shape would be a great improvement for us in order to have better accuracy and lower cpu time consumption.
For example : when it come into simulating an IMU sensor, tessellated cylinder provide very chaotic data for the elevation as wheels always bounce to the ground whatever we tune it.
Also, it implicitly provoke slip : vehicle speed (ground speed) is lower than the target speed provided.
In order to remove these issues we sometime have to replace the wheels by spheres but it only move the problem to another place because vehicles may be larger than expected and won't respond accordingly to LIDAR sensors for example.
Don't forget that PhysX engine may be used for other things than video games.

**Comment by kstorey-nvidia** [comment]
PhysX supports sphere-swept shapes, e.g. sphere-swept box (lozenge) and sphere-swept convex. It is fairly straightforward to use these - increase contact offset and rest offset on the shape, with rest offset corresponding to the amount by which you want to inflate the shape.

You could utilize a thin disk with a rest offset and achieve a rounded cylindrical shape that should hopefully suffer from fewer discretization artefacts.

**Comment by Chico63** [comment]
Modifying contact offset and rest offset has already been tested several times and does not improve our behavior. We need a perfect cylinder shape for our purpose, nothing less.

**Comment by coffeenotfound** [comment]
Maybe as a compromise it would be great if PhysX added a utility function for generating such a cylinder mesh

**Comment by vreutskyy** [comment]
The latest [PhysX SDK 5.5.0](https://github.com/NVIDIA-Omniverse/PhysX) has recently introduced [PxConvexCoreGeometry](https://nvidia-omniverse.github.io/PhysX/physx/5.5.0/_api_build/classPxConvexCoreGeometry.html#pxconvexcoregeometry). It allows simulation of cylinders, among the other quadric shapes.

**Comment by coffeenotfound** [comment]
Does it really allow cylinders though? As far as I understood you could only make capsules via a line as core and a margin as radius
