### ISSUE TITLE
Download/Build PhysX 4.0 SDK Binaries

### ISSUE THREAD

**Issue by tomerze** [NVIDIAGameWorks/PhysX#68]
For some reason generate_projects.bat does not generate for me a visual studio sln file and proj files to build PhysX 4.0 .

Where can I find a download to PhysX's binaries or to a already generated sln file and proj files ?

**Comment by AlesBorovicka** [comment]
I am not quite sure that I understand your issue.
We do not ship binaries anymore since the source code is now here on github.
What step does not work for you when you generate your project files?

 * Solutions are generated through a script in physx root directory: generate_projects.bat
 * Script generate_projects.bat expects a preset name as a parameter, if a parameter is not provided it 
    does list the available presets.
 * Supported presets for windows platform are: vc12win32, vc12win64, vc14win32, vc14win64, vc15win32, vc15win64.
 * Generated solutions are in folder compiler/"preset name"

**Comment by tomerze** [comment]
The only sln file I found after running generate_projects.bat was 

PhysX-4.0\physx\compiler\vc15win64\CMakeFiles\3.13.2\CompilerIdCXX.sln

When I open and build it in Visual Studio nothing happens. Am I miss using it ?

**Comment by liedtkeInTUM** [comment]
the sln file you need for build all libs you should find in PhysX-4.0\physx\compiler\vc15win64\PhysXSDK.sln. If not, your generation process seems to be broken. For me it works following that http://gameworksdocs.nvidia.com/PhysX/4.0/documentation/PhysXGuide/Manual/BuildingWithPhysX.html#generating-projects-with-cmake guide

**Comment by wilflalonde** [comment]
After running generateProjects.bat, getting file PhysXSDK.sln, and building successfully
without errors, I have 8 files in bin of the form win.x86_32.vc141.mt (141 doesn't mean anything
to me). Only this one has libs in it. I'm failing to link because the linker is looking for 
PhysX3CHECKED_x86.lib which I believe is a lib from an old version of PhysX.  It's not in the 
libs with vc141.mt and all my libs are together in one directory. The project's properties don't 
reference any other location for libs. So it must be coming from one of the generated libs. 
So far, I'm stumped...

**Comment by AlesBorovicka** [comment]
Yes, this has changed. The produced libs do not have the configuration name appended. The libraries have same name and are in different directories for each configuration. 
The number in the directory name are Visual studio toolset versions, note that in your case you used Visual Studio 2017 that does have the toolset version 141.

**Comment by wilflalonde** [comment]
Thanks very much... I finally found my problem. My BAD.

As for the other person who was having problems too, it looked
like the same problem I had earlier, namely that MAKE was not
properly installed which I figured out by executing "make -version".
It essentially told me to re-install.

Wilf

**Comment by PcChip** [comment]
I'm having the same issue, when I run the batch file nothing happens (doesn't prompt for input, doesn't take input when I try giving it as an argument)  
  
update: I was able to workaround this issue by running the following from cmd prompt:  
c:\Python27\python.exe c:\project\physX-4.1\physx\buildtools\cmake_generate_projects.py vc16win64  
  
edit2: although when I open the sln file and build the "ALL_BUILD", I get 4 succeeded, 55 failed  
  
edit3: sorry to keep spamming here, but I think this is the issue:  
https://developercommunity.visualstudio.com/content/problem/734566/msvc-142328019-is-missing-include-typeinfoh.html  
  
edit4: indeed, renaming <typeinfo.h> to \<typeinfo> in PsAllocator.h fixed it and built everything  
  
What a journey!
